In [4]:
import numpy as np
import math
from astropy.table import Table, Column

In [8]:
def randomize(n):
    num=np.array(range(1,n+1))
    arr=np.random.choice(num,size=n,replace=False)
    print(arr)
    return arr

def numflips(n,arr):
    if n<0:
        print("Please give an n greater than 0")
        
    flipCount=0
    
    p=n
    if n%2==1:
        p=n-1
    
    for i in range(0,p,2):
        item=arr[i]
        item2=arr[i+1]
        
        for ii in range(i+1,n):
            select=arr[ii]
            
            if item>select:
                flipCount+=1
            if item2>select:
                flipCount+=1
    return flipCount

In [9]:
def Merge(A,p,q,r):
    i=0
    j=0
    k=p
    
    x=q-p+1
    y=r-q
    l=np.zeros(x)
    r=np.zeros(y)
    
    flip=0
    
    for w in range(0,x):
        l[w]=A[p+w]
    for z in range(0,y):
        r[z]=A[q+1+z]
    
    while i<x and j<y:
        if l[i]<=r[j]:
            A[k]=l[i]
            i+=1
        else:
            for v in range(i,x):
                if l[v]>r[j]:
                    flip+=1
            A[k]=r[j]
            j+=1
        k+=1
       
    while i<x:
        A[k]=l[i]
        i+=1
        k+=1
    while j<y:
        A[k]=r[j]
        j+=1
        k+=1
    return flip,A
            
def MergeSort(A,p,r):
    lCount=0
    rCount=0
    q=math.floor((p+r)/2)
    e=0
    if p<r:
        lCount=MergeSort(A,p,q)
        rCount=MergeSort(A,q+1,r)
        e,ce=Merge(A,p,q,r)
        A=ce
        return e+lCount+rCount
    return 0

In [10]:
flipA=np.zeros(12,dtype=int)
flipM=np.zeros(12,dtype=int)
nVal=np.zeros(12,dtype=int)
table=Table()

for qwerty in range(1,13):
    pu=randomize(2**qwerty)
    nVal[qwerty-1]=2**qwerty
    flipA[qwerty-1]=numflips(2**qwerty,pu)
    flipM[qwerty-1]=MergeSort(pu,0,(2**qwerty)-1)

table["N"]=nVal
table["Flips"]=flipA
table["MergeFlips"]=flipM
print(table)

[2 1]
[4 2 3 1]
[5 3 6 2 7 4 1 8]
[ 1 16  4  3 13  6  7 14  9 12  2 10  5 15 11  8]
[12  5 23 27 30 24 21 26  1 22 13 17 28  7  4 11 19  3  2 10 15 20 31  6
 14  9 16 29 32 18  8 25]
[44  4  7 47 18 35 34  9 48  8 39 46 43 23 28 10 42 24 60 17 30 25 61 45
 31 64 38 33 36  6 20 29 40 15 12 54 41 22 55 50  5 19  3 13 51 58 49 63
 62  1 57 11 32 16 53 14 56 21 52 27 59 37  2 26]
[ 84  35  83  31  14 110  21  82  72  40 101  45 118  41  62  17  81  57
  71  26   2  76  94  20 107 112 117  36  29  53  16 125 126 123  98  79
   8  13  19  60  47   7  22  97  61  58  34  39  66 114 113 100  67 116
  88  91  70  51  10 127  87 122  48  65 115 106   1  95  15  50  93  32
  77  92  24 109  90  43   9  27   5  23  46  33  69  12  52  25 103  18
  78  75  56 119  54 104  42 124 128 121   4  89  55 105  44 120  86 102
   6  11 111   3  85  30  68  80  49  64 108  96  99  63  74  73  59  38
  37  28]
[134 106 201  31 103 166  33  94  83 173  57 117 237  65 151 122 149 199
 111 190 250 152 159 180  7